import { UIProvider } from '@/providers/next-ui-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextThemeProvider } from '@/providers/theme-provider'
import Navbar from '@/components/common/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextThemeProvider>
          <UIProvider>
            <Navbar />
            {children}
          </UIProvider>
        </NextThemeProvider>
      </body>
    </html>
  )
}
